name: Build
on:
  workflow_dispatch:
    inputs:
      ipa_url:
        description: "URL to the decrypted IPA file"
        default: ""
        required: true
        type: string

      display_name:
        description: "App Name (Optional)"
        default: "YouTube"
        required: true
        type: string

      bundle_id:
        description: "Bundle ID (Optional)"
        default: "com.google.ios.youtube"
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - name: Hide Sensitive Inputs
        uses: levibostian/action-hide-sensitive-inputs@v1
        with:
          exclude_inputs: bundle_id,display_name

      - name: Download and Validate IPA
        run: |
          wget "${{ inputs.ipa_url }}" --quiet --no-verbose -O youtube.ipa
          file_type=$(file --mime-type -b youtube.ipa)
          if [[ "$file_type" != "application/x-ios-app" && "$file_type" != "application/zip" ]]; then
            echo "::error::Validation failed: The downloaded file is not a valid IPA. Detected type: $file_type."
            exit 1
          fi

      - name: Get YouTube Version 
        run: |
          unzip -q youtube.ipa -d ytextracted
          echo "YT_VERSION=$(grep -A 1 '<key>CFBundleVersion</key>' ytextracted/Payload/YouTube.app/Info.plist | grep '<string>' | awk -F'[><]' '{print $3}')" >> $GITHUB_ENV

      - name: Install Dependencies
        run: brew install make ldid swiftlint

      - name: Set PATH Environment Variables
        run: |
          echo "$(brew --prefix make)/libexec/gnubin" >> $GITHUB_PATH
          echo "THEOS=${{ github.workspace }}/theos" >> $GITHUB_ENV

      - name: Clone Theos
        run: git clone --quiet --depth=1 --recurse-submodules https://github.com/theos/theos.git

      - name: Download iOS SDK
        run: |
          git clone --quiet --depth=1 -n --filter=tree:0 https://github.com/xybp888/iOS-SDKs.git
          cd iOS-SDKs
          git sparse-checkout set --no-cone iPhoneOS18.6.sdk
          git checkout
          mv *.sdk $THEOS/sdks

      - name: Install cyan and tbd
        run: |
          pipx install --force https://github.com/asdfzxcvbn/pyzule-rw/archive/main.zip
          wget --quiet --no-verbose "https://github.com/inoahdev/tbd/releases/download/2.2/tbd-mac" -O /usr/local/bin/tbd
          chmod +x /usr/local/bin/tbd 

      - name: Clone Open in YouTube (Safari Extension)
        run: |
          git clone --quiet -n --depth=1 --filter=tree:0 https://github.com/BillyCurtis/OpenYouTubeSafariExtension.git
          cd OpenYouTubeSafariExtension
          git sparse-checkout set --no-cone OpenYouTubeSafariExtension.appex
          git checkout
          mv *.appex ${{ github.workspace }}

      - name: Clone YouTubeHeader
        run: git clone --quiet --depth=1 https://github.com/PoomSmart/YouTubeHeader.git $THEOS/include/YouTubeHeader

      - name: Clone PSHeader
        run: git clone --quiet --depth=1 https://github.com/PoomSmart/PSHeader.git $THEOS/include/PSHeader

      - name: Clone YouMod
        run: git clone --quiet --depth=1 https://github.com/Tonwalter888/YouMod.git

      - name: Clone YouGroupSettings
        run: git clone --quiet --depth=1 https://github.com/PoomSmart/YouGroupSettings.git

      - name: Build YouMod
        run: |
          cd YouMod
          make clean package DEBUG=0 FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          mv packages/*.deb ${{ github.workspace }}/youmod.deb

      - name: Build YouGroupSettings
        run: |
          cd YouGroupSettings
          make clean package DEBUG=0 FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          mv packages/*.deb ${{ github.workspace }}/ygs.deb

      - name: Inject Tweaks Into IPA
        run: |
          tweaks="OpenYouTubeSafariExtension.appex"
          for f in *.deb; do
            tweaks="$tweaks $f"
          done
          cyan -i youtube.ipa -o PkdL_${{ env.YT_VERSION }}.ipa -uwef $tweaks -n "${{ inputs.display_name }}" -b ${{ inputs.bundle_id }}

      - name: Create a Draft Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: pkdl-${{ github.run_number }}
          name: PkdL ${{ env.YT_VERSION }} (${{ github.run_number }})
          files: PkdL_${{ env.YT_VERSION }}.ipa
          draft: true
